{
'name': 'Ip Visitor Traking',
'version': '1.0',
'summary': 'Integración con la API de OpenWeatherMap',
'description': 'Obtención de información sobre la geolocalización de los visitantes de la web oficial.',
'author': 'Manuel Ripalda',
'category': 'Website',
'depends': ['base'],
'data': ['security/ir.model.access.csv',
         'views/ip_traker_view.xml',
        ],
'installable': True,
'application': True,
'license': 'LGPL-3',
'icon': '/ip_visitor_traking/static/description/icon.png',
}